function(add_recursive current_dir sources_files)
    file(GLOB children RELATIVE ${PROJECT_SOURCE_DIR}/${current_dir} ${PROJECT_SOURCE_DIR}/${current_dir}/*)
    foreach(child ${children})
        if(IS_DIRECTORY ${PROJECT_SOURCE_DIR}/${current_dir}/${child})
            add_recursive(${current_dir}/${child} ${sources_files})
        else()
            get_filename_component(extension ${child} EXT)
            if (NOT extension STREQUAL "")
                string(REGEX MATCHALL "^.*.[h|hpp|c|cpp|cxx]" out ${extension})
                if (NOT out STREQUAL "")
                    if(MSVC)
                        string(REPLACE "/" "\\" groupname ${current_dir})
                    endif()
                    set(filename ${PROJECT_SOURCE_DIR}/${current_dir}/${child})
                    source_group(${groupname} FILES ${filename})
                    set(${sources_files} ${${sources_files}} ${filename})
                endif()    
            endif()
        endif()        
    endforeach()
    set(${sources_files} ${${sources_files}} PARENT_SCOPE)
endfunction(add_recursive)