function(initialize_conan_repositories)
    conan_check() 
    conan_add_remote(NAME conan-center URL https://conan.bintray.com)
    conan_add_remote(NAME qt URL https://api.bintray.com/conan/quark/conan-qt)
    conan_add_remote(NAME poco URL https://api.bintray.com/conan/pocoproject/conan)
    conan_add_remote(NAME boost URL https://api.bintray.com/conan/conan-community/conan)
    conan_add_remote(NAME mysql URL https://api.bintray.com/conan/bincrafters/public-conan)
    conan_add_remote(NAME ogre3d URL https://api.bintray.com/conan/sixten-hilborn/public-conan)
endfunction()